{{- if .Values.enableArgoRollouts }}
{{- $instance := include "progressive.fullname" . -}}

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $instance }}
  labels:
    {{- include "progressive.labels" . | nindent 4 }}
spec:
  args:
  - name: service
  metrics:
  - name: {{ $instance }}
    {{- with .Values.analysys }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

{{- end }}