{{- if .Values.enableIstio }}
{{- $instance := include "progressive.fullname" . -}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ $instance }}
  labels:
    {{- include "progressive.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ $instance }}
  action: {{ .Values.access.authorization.action }}
  rules:
    {{- with .Values.access.authorization.rules }}
    {{- toYaml . | nindent 2 }}
    {{- end }}

{{- end }}