{{- if .Values.enableIstio }}
{{- $instance := include "progressive.fullname" . -}}

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $instance }}
  labels:
    {{- include "progressive.labels" . | nindent 4 }}
spec:
  host: {{ $instance }}
  trafficPolicy:
    tls:
      mode: {{ .Values.access.authentication.destinationRule }}
  subsets:
  - name: stable
    labels:
      app: {{ $instance }}
  - name: canary
    labels:
      app: {{ $instance }}

{{- end }}