{{- if .Values.enableIstio }}
{{- $instance := include "progressive.fullname" . -}}

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $instance }}
  labels:
    {{- include "progressive.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.gateway.instance }}
    istio: {{ .Values.gateway.instance }}
  servers:
  - hosts:
    - {{ .Values.gateway.hostname }}
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: {{ .Values.gateway.mode }}
      credentialName: {{ .Values.gateway.secret }}

{{- end }}