{{- if .Values.enableIstio }}
{{- $instance := include "progressive.fullname" . -}}

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ $instance }}
  labels:
    {{- include "progressive.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.access.authentication.peerAuthentication }}

{{- end }}