{{- $instance := include "progressive.fullname" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $instance }}
  labels:
    {{- include "progressive.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ $instance }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
