{{- if .Values.enableIstio }}
{{- $instance := include "progressive.fullname" . -}}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $instance }}
  labels:
    {{- include "progressive.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ $instance }}
  - {{ .Values.gateway.hostname }}
  gateways:
  - mesh
  - {{ $instance }}
  http:
  - name: {{ $instance }}
    fault:
      abort:
        httpStatus: 500
        percentage:
          value: {{ .Values.service.fault.percentage }}
    route:
    - destination:
        host: {{ $instance }}
        subset: stable
      weight: 100
    - destination:
        host: {{ $instance }}
        subset: canary
      weight: 0

{{- end }}